# Generated by Django 5.2.7 on 2025-10-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='ai_signal_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
