# Generated by Django 5.2.7 on 2025-10-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_trade_ai_confidence_trade_ai_signal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('trade_pnl', 'Trade P&L')], max_length=20),
        ),
    ]
