# Generated by Django 5.2.7 on 2025-10-09 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawalWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(choices=[('USD', 'USD'), ('ZWL', 'ZWL')], max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Transfer'), ('transferred', 'Transferred to Bank'), ('redeposited', 'Re-deposited to Trading')], default='pending', max_length=20)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=100)),
                ('account_holder', models.CharField(blank=True, max_length=255)),
                ('transfer_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transferred_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
