# Generated by Django 5.2.7 on 2025-10-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_withdrawalwallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='ai_signal_type',
            field=models.TextField(blank=True, null=True),
        ),
    ]
