# Generated by Django 5.2.7 on 2025-10-11 19:40

import json
import ast
from django.db import migrations, models


def convert_python_dict_to_json(apps, schema_editor):
    """
    Convert Python dict strings to valid JSON format before changing field type.
    Python dicts use single quotes: {'key': 'value'}
    JSON requires double quotes: {"key": "value"}
    """
    Trade = apps.get_model('api', 'Trade')
    
    converted_count = 0
    skipped_count = 0
    
    for trade in Trade.objects.all():
        if trade.ai_signal_type:
            try:
                # Try to parse as JSON first (if already valid)
                try:
                    parsed_data = json.loads(trade.ai_signal_type)
                except (json.JSONDecodeError, TypeError):
                    # Fall back to Python dict parsing
                    parsed_data = ast.literal_eval(trade.ai_signal_type)
                
                # Convert to valid JSON string
                trade.ai_signal_type = json.dumps(parsed_data)
                trade.save(update_fields=['ai_signal_type'])
                converted_count += 1
                
            except Exception as e:
                print(f"Warning: Could not convert trade {trade.id} ai_signal_type: {e}")
                skipped_count += 1
    
    print(f"Converted {converted_count} trades to JSON format, skipped {skipped_count}")


def reverse_migration(apps, schema_editor):
    """No reverse needed - JSONField stores as text anyway"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_trade_ai_signal_type'),
    ]

    operations = [
        # Step 1: Convert Python dict strings to valid JSON format
        migrations.RunPython(
            convert_python_dict_to_json,
            reverse_migration,
        ),
        # Step 2: Change field type to JSONField (now data is valid JSON)
        migrations.AlterField(
            model_name='trade',
            name='ai_signal_type',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
