# Generated by Django 5.2.7 on 2025-10-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_change_ai_signal_type_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='quantity',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
