# Generated by Django 5.2.7 on 2025-10-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_change_quantity_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='instrument_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('option', 'Option'), ('forex', 'Forex')], max_length=20),
        ),
    ]
