# Generated by Django 5.2.7 on 2025-10-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_forex_ai_trading_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='broker_deal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
