# Generated by Django 5.2.7 on 2025-10-24 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_trade_broker_deal_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradableInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('market', models.CharField(choices=[('US', 'United States'), ('EU', 'European Union')], max_length=10)),
                ('exchange', models.CharField(choices=[('NYSE', 'New York Stock Exchange'), ('NASDAQ', 'NASDAQ'), ('XETRA', 'Deutsche Börse XETRA (Germany)'), ('LSE', 'London Stock Exchange'), ('EURONEXT', 'Euronext (France)')], max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['market', 'symbol'],
            },
        ),
        migrations.AddField(
            model_name='trade',
            name='broker',
            field=models.CharField(choices=[('alpaca_sim', 'Alpaca (Simulated)'), ('capital_stock', 'Capital.com (Stock)'), ('capital_forex', 'Capital.com (Forex)')], default='alpaca_sim', max_length=20),
        ),
        migrations.CreateModel(
            name='BrokerAccountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(choices=[('alpaca_sim', 'Alpaca (Simulated)'), ('capital_stock', 'Capital.com (Stock)'), ('capital_forex', 'Capital.com (Forex)')], max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('available_funds', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
                'unique_together': {('user', 'broker')},
            },
        ),
    ]
