# Generated by Django 5.2.7 on 2025-10-25 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_tradableinstrument_trade_broker_brokeraccountsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradableinstrument',
            name='exchange',
            field=models.CharField(choices=[('NYSE', 'New York Stock Exchange'), ('NASDAQ', 'NASDAQ'), ('XETRA', 'Deutsche Börse XETRA (Germany)'), ('LSE', 'London Stock Exchange'), ('EURONEXT', 'Euronext (France)'), ('TSE', 'Tokyo Stock Exchange'), ('HKEX', 'Hong Kong Stock Exchange'), ('SGX', 'Singapore Exchange'), ('NSE', 'National Stock Exchange of India'), ('BSE', 'Bombay Stock Exchange'), ('ASX', 'Australian Securities Exchange'), ('JSE', 'Johannesburg Stock Exchange'), ('OTHER', 'Other Exchange')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='tradableinstrument',
            name='market',
            field=models.CharField(choices=[('US', 'United States'), ('EU', 'European Union'), ('JP', 'Japan'), ('HK', 'Hong Kong'), ('SG', 'Singapore'), ('IN', 'India'), ('AU', 'Australia'), ('ZA', 'South Africa')], max_length=10),
        ),
    ]
