# Generated by Django 5.2.7 on 2025-10-31 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_tradableinstrument_exchange_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlpacaEquitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=15)),
                ('unrealized_pl', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alpaca_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alpaca_equity_snapshots',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='alpaca_equi_user_id_3149ff_idx')],
            },
        ),
    ]
