# Generated by Django 5.2.7 on 2025-11-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alpacaequitysnapshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='option_type',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='premium',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='strike_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='underlying_asset',
        ),
        migrations.AddField(
            model_name='alpacaequitysnapshot',
            name='daily_pl',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='trade',
            name='broker',
            field=models.CharField(choices=[('alpaca_sim', 'Alpaca (Simulated)')], default='alpaca_sim', max_length=20),
        ),
        migrations.AlterField(
            model_name='trade',
            name='instrument_type',
            field=models.CharField(choices=[('stock', 'Stock'), ('forex', 'Forex')], max_length=20),
        ),
        migrations.DeleteModel(
            name='WithdrawalWallet',
        ),
    ]
