# Generated by Django 5.2.7 on 2025-10-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_trading_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
