# Generated by Django 5.2.7 on 2025-10-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_approval_status_user_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='capital_api_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='capital_password',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='capital_username',
            field=models.TextField(blank=True, null=True),
        ),
    ]
