# Generated by Django 5.2.7 on 2025-10-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_capital_api_key_user_capital_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='capital_use_demo',
            field=models.BooleanField(default=True),
        ),
    ]
