# Generated by Django 5.2.7 on 2025-10-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_capital_use_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='forex_ai_trading_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
