# Generated by Django 5.2.7 on 2025-10-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_forex_ai_trading_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='capital_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
