# Generated by Django 5.2.7 on 2025-10-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_capital_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='capital_ai_trading_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
