# Generated by Django 5.2.7 on 2025-10-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_capital_ai_trading_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='autonomous_trading_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
