# Generated by Django 5.2.7 on 2025-11-03 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_autonomous_trading_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='autonomous_trading_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='capital_account_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='capital_ai_trading_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='capital_api_key',
        ),
        migrations.RemoveField(
            model_name='user',
            name='capital_password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='capital_use_demo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='capital_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='forex_ai_trading_enabled',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usd_balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='zwl_balance',
        ),
    ]
