# Generated by Django 5.2.7 on 2025-11-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_autonomous_trading_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ml_bootstrap_mode',
            field=models.BooleanField(default=True, help_text='Bootstrap mode: allows AI trading without ML model (uses technical analysis only). Auto-disables once ML model is trained.'),
        ),
    ]
