# Generated by Django 5.2.1 on 2025-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_ml_bootstrap_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='autonomous_trading_enabled',
            field=models.BooleanField(default=False, help_text='Enable 24/7 autonomous trading agent that executes trades automatically during market hours'),
        ),
    ]
