"""
Django settings for trading_platform project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Default to False for security, set DEBUG=True only in development
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        "DJANGO_SECRET_KEY environment variable must be set. "
        "Generate one with: python -c 'from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())'"
    )

# ALLOWED_HOSTS: Allow requests from any domain
# For production, you can optionally set specific hosts via ALLOWED_HOSTS env var
# Example: ALLOWED_HOSTS=your-app.replit.app,custom-domain.com
allowed_hosts_env = os.getenv('ALLOWED_HOSTS', '')
if allowed_hosts_env:
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_env.split(',') if host.strip()]
else:
    ALLOWED_HOSTS = ['*']
# Security settings for production
# These default to secure values for production deployment
# Disabled in DEBUG mode for development servers that don't support HTTPS

if DEBUG:
    # Development mode - disable HTTPS enforcement (dev server doesn't support HTTPS)
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_PROXY_SSL_HEADER = None
else:
    # Production mode - enable HTTPS security with Replit compatibility
    # Trust Replit's proxy for HTTPS detection (prevents redirect loops)
    # Replit's proxy terminates TLS and forwards HTTP with X-Forwarded-Proto: https
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    
    # HTTPS security settings - ENABLED by default for production
    # Replit handles SSL termination at proxy, these settings secure cookies and headers
    SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'  # Keep False - Replit proxy handles this
    SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', 'True') == 'True'  # ✅ Enabled
    CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', 'True') == 'True'  # ✅ Enabled
    SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '31536000'))  # ✅ 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'True') == 'True'  # ✅ Enabled
    SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'True') == 'True'  # ✅ Enabled


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'accounts',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'trading_platform.middleware.NoCacheMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trading_platform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trading_platform.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration - disable caching for HTML files to prevent stale content
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_INDEX_FILE = False  # Disable index-file handling so middleware can add headers
WHITENOISE_IMMUTABLE_FILE_TEST = lambda path, url: False  # Disable immutable files (always check for updates)

# Custom header function for WhiteNoise to force no-cache on HTML files
def whitenoise_add_no_cache_headers(headers, path, url):
    """
    Add AGGRESSIVE no-cache headers for HTML files
    This prevents browsers from caching stale HTML that could show old errors
    
    CRITICAL: Without these headers, users may see "Internal Server Error" from cached content
    """
    if path.endswith('.html') or path.endswith('index.html') or url == '/':
        # Triple-layer cache prevention
        headers['Cache-Control'] = 'no-cache, no-store, must-revalidate, max-age=0, private'
        headers['Pragma'] = 'no-cache'
        headers['Expires'] = '0'
        headers['Surrogate-Control'] = 'no-store'
        
        # Prevent ETag caching
        if 'ETag' in headers:
            del headers['ETag']
    else:
        # Allow caching for JS/CSS/images (they have hashed filenames)
        headers['Cache-Control'] = 'public, max-age=31536000, immutable'
    
    return headers

WHITENOISE_ADD_HEADERS_FUNCTION = whitenoise_add_no_cache_headers

# React build directory
REACT_BUILD_DIR = os.path.join(BASE_DIR.parent, 'dist')

# Serve React static files
STATICFILES_DIRS = [
    REACT_BUILD_DIR,
] if os.path.exists(REACT_BUILD_DIR) else []

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'accounts.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'accounts.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# CORS Configuration
# CRITICAL: CORS_ALLOW_ALL_ORIGINS with CORS_ALLOW_CREDENTIALS is a severe security risk
# In production, explicit origins MUST be configured via CORS_ALLOWED_ORIGINS env var

cors_origins_env = os.getenv('CORS_ALLOWED_ORIGINS', '')
if cors_origins_env:
    # Explicit allowed origins (production-safe)
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in cors_origins_env.split(',')]
    CORS_ALLOW_CREDENTIALS = True
elif DEBUG:
    # Development only: Allow all origins
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = True
else:
    # Production without CORS_ALLOWED_ORIGINS: Disable cross-origin credentials
    # This prevents credential theft via cross-origin attacks
    CORS_ALLOW_ALL_ORIGINS = True
    CORS_ALLOW_CREDENTIALS = False
    # Log warning for missing configuration
    import logging
    logging.warning(
        "PRODUCTION MODE: CORS_ALLOWED_ORIGINS not set. "
        "Cross-origin requests allowed but credentials disabled for security. "
        "Set CORS_ALLOWED_ORIGINS environment variable to enable credentialed requests."
    )

# CSRF Trusted Origins - Required for cross-origin requests
csrf_origins_env = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if csrf_origins_env:
    # Production: Use specific trusted origins from env
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in csrf_origins_env.split(',')]
elif DEBUG:
    # Development: Trust local origins
    CSRF_TRUSTED_ORIGINS = [
        'http://localhost:5000',
        'http://127.0.0.1:5000',
        'http://0.0.0.0:5000',
    ]
else:
    # Production fallback: Trust Replit domain
    CSRF_TRUSTED_ORIGINS = [
        'https://*.replit.app',
        'https://*.replit.dev',
    ]

# ML Training Configuration
# Cutoff date for excluding corrupted historical trades from ML training
# Only trades created on or after this date will be used for model training
# Format: ISO-8601 (YYYY-MM-DD) - parsed with timezone awareness
from datetime import datetime, timezone

ML_TRAINING_CUTOFF_DATE_STR = os.getenv('ML_TRAINING_CUTOFF_DATE', '2000-01-01')  # Changed from 2025-11-11 to include all trades
try:
    ML_TRAINING_CUTOFF_DATE = datetime.fromisoformat(ML_TRAINING_CUTOFF_DATE_STR).replace(tzinfo=timezone.utc)
except ValueError:
    import logging as _logging
    _logging.warning(
        f"Invalid ML_TRAINING_CUTOFF_DATE format: {ML_TRAINING_CUTOFF_DATE_STR}. "
        "Using default: 2025-11-11. Expected format: YYYY-MM-DD"
    )
    ML_TRAINING_CUTOFF_DATE = datetime(2025, 11, 11, tzinfo=timezone.utc)

if not os.getenv('ML_TRAINING_CUTOFF_DATE'):
    import logging as _logging
    _logging.warning(
        f"ML_TRAINING_CUTOFF_DATE not set. Using default: {ML_TRAINING_CUTOFF_DATE.date()}. "
        "This excludes trades before this date from ML training to prevent corrupted data from poisoning the model."
    )
